/* soapClient.cpp
   Generated by gSOAP 2.8.7 from /home/raziel/proyectos/soap/prueba1/cliente/include/soap/Cliente.hpp

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.7 2013-04-14 08:59:52 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hello(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__hello *ns1__hello_, ns1__helloResponse *ns1__helloResponse_)
{	struct __ns1__hello soap_tmp___ns1__hello;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost:8080/servidor/servidor";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__hello.ns1__hello_ = ns1__hello_;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__hello(soap, &soap_tmp___ns1__hello);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__hello(soap, &soap_tmp___ns1__hello, "-ns1:hello", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__hello(soap, &soap_tmp___ns1__hello, "-ns1:hello", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__helloResponse_)
		return soap_closesock(soap);
	ns1__helloResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__helloResponse_->soap_get(soap, "ns1:helloResponse", "ns1:helloResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
